name: courses_mobile_rsbf
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  dio: ^5.4.3+1
  alfred: ^1.1.1
  envied: ^0.5.4+1
  # path: ^1.8.0
  dart_eval: ^0.7.9
  bob_design_system:
    path: ../bob-design-system

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  lints: ^3.0.0
  test: ^1.24.0
